### ISSUE TITLE
关于标题

### ISSUE THREAD

**Issue by portgas-an** [swlfigo/HackintoshEFI#1]
建议把标题改改,这样可以在github上面让更多的人搜索出来

**Comment by swlfigo** [comment]
@qq2253563  你好谢谢关注，本仓库打算放我装过不同机型成功案例的驱动集合，由于三大件(CPU+主板+显卡)型号特别的长,随着以后可能装机数量增多是不可能完全列举出来的,所以我尽可能再完善 ReadMe 文档, 或者有什么好的建议欢迎探讨一下。
另外 不同机型安装的文章详情都会在我的博客上发表,欢迎指正
[博客地址](http://isylar.com/)
