### ISSUE TITLE
关于Z270-AR config.plist的疑问

### ISSUE THREAD

**Issue by jimalex8877** [swlfigo/HackintoshEFI#3]
你好，up主，我的主板和你一样、显卡是RX570、CPU是i5-7500。
1. USBInjectAll.kext应该是不需要的，Z系列芯片主板对于黑苹果一般所有USB端口都是默认打开的，B系列才需要它，希望对你有用~
2. 我的Catalina睡眠死机，BIOS关闭串口后，睡眠唤醒后直接卡死重启，看UP主配置Audio注入1？我注入的是5，重置HDA没点，不知道是否跟AppleALC.kext是否有关系。回家我试试，谢谢~
3. up主的efi是否有些过多？

**Comment by swlfigo** [comment]
@changmingjiang 
1. 因为从10.13.n 开始第一次研究黑苹果时候都是放入  USBInjectAll.kext , 而且一直没有什么问题，所以以后升级都是留下了，去掉应该是可以的
2. 关于重启, 业界好像都用 HibernationFixup.kext  ， 但是我没放，我睡眠重启是没死机，HDA问题，应该是要点击的，这样就会加载AppleALC的layout,但是感觉不是导致卡死的问题。也有可能我改过bios设置？我是之前升级过bios到最新版，而且也看过youtube一些 bios调整方案的.
[传送门](https://www.youtube.com/watch?v=h0Xo_WyzfeQ&t=473s)
2.1 看了下[applealc s1220a](https://github.com/acidanthera/AppleALC/tree/master/Resources/ALCS1220A) 中, layoutid = 1 10个月前更新了， layouid =5 2年前~ 好像1比较好哦~当然这个看你觉得哪个音质比较好了
3. 关于efi. AppleImageCodec.efi ; AppleKeyAggregator.efi ; AppleUITheme.efi 这3个的确不用的，我是看到说UI效果好点才加入.其他的我都是按网上主流默认需要的加进去.
(virtualsmc，apfsdriverloader,aptiomemoryfix必须, fsinject是加载驱动好像.其他好像是读取特别分区的驱动，是不需要也行的.)
希望能帮助到你！

**Comment by jimalex8877** [comment]
谢谢up主，layoutid = 1音质确实好，已使用~
关于睡眠问题终于找到解决办法了，https://github.com/acidanthera/bugtracker/issues/513 有讨论
在内核补丁中添加：
`Find: 63 6F 6D 2E 61 70 70 6C 65 00 5F 5F 6B 65 72 6E 65 6C 5F 5F 00`
`Repl: 6E 6F 74 2E 61 70 70 6C 65 00 5F 5F 6B 65 72 6E 65 6C 5F 5F 00`

up主似乎没有开启核显？这可能就避免了hdmi hda的开启，所以没有引起睡眠死机的问题

**Comment by swlfigo** [comment]
@changmingjiang 
Bios我是选了PEG应该就是屏蔽了核显了,直接用580也不错哦
另外我在VideoProc中也能看到核显，能4k硬解意思了，而且工作(本人码农不是剪片)，玩游戏(Dota2高配,VM虚拟机steam游戏)没什么影响~
![pic](http://sylarimage.oss-cn-shenzhen.aliyuncs.com/2019-10-14-135243.png)
