### ISSUE TITLE
b360m主板可以替换为（ASUS）TUF B360-PRO GAMING(WI-FI)  这个主板吗

### ISSUE THREAD

**Issue by snaigle** [swlfigo/HackintoshEFI#6]
b360m主板可以替换为（ASUS）TUF B360-PRO GAMING(WI-FI)  这个主板吗
我现在电脑配置是 9400f+ asus-b360-pro-wifi  + rx590 
主板能否兼容

**Comment by swlfigo** [comment]
带WIFI的板子，WIFI都驱动不了，其他应该是没问题的，装过几台其他牌子的360 360 都可以直接上,你可以先用U盘烤个EFI看下能不能进入安装界面，可以的话基本没啥问题了,记得替换三码

**Comment by swlfigo** [comment]
@snaigle 带WIFI的板子，WIFI都驱动不了，其他应该是没问题的，装过几台其他牌子的360 360 都可以直接上,你可以先用U盘烤个EFI看下能不能进入安装界面，可以的话基本没啥问题了,记得替换三码

**Comment by snaigle** [comment]
多谢，我先试试
